global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# NOTE: you may have to replace the `host.docker.internal` by `localhost` if you run on Linux.
# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'fights'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'heroes'
    static_configs:
      - targets: ['host.docker.internal:8083']
  - job_name: 'villains'
    static_configs:
      - targets: ['host.docker.internal:8084']
# end::adocPrometheus[]
