global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'fights'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'heroes'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8083']
  - job_name: 'villains'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8084']
# end::adocPrometheus[]
